config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  # mostly resource under space namespace
  resources :spaces, only: [:new, :create, :index] do
    resources :pipelines, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        get 'configuration'
      end
      resources :actions, only: [:new, :create], module: :pipelines
    end

    resources :actions, only: [:index, :show] do
      member do
        post 'rebuild'
      end
    end
    resources :templates, only: [:index]
  end

  get '/repos/github_repos', to: 'repos#github_repos', as: 'github_repos'

  get 'dashboard', to: 'dashboard#index'
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :check_user_current_space

  def index
    # remember space_id
    cookies[:space_id] ||= params[:space_id]
    redirect_to space_actions_path
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/dashboard/_footer.html.erb
<% if false %>
  <footer class="footer">
    <div class="footer-block buttons">
    </div>
    <div class="footer-block author">
      <ul>
        <li> created by <a href="https://github.com/jjyr">jjy</a></li>
      </ul>
    </div>
  </footer>
<% end %>

app/views/layouts/dashboard/_header.html.erb
<header class="header">
  <div class="header-block header-block-collapse hidden-lg-up">
    <button class="collapse-btn" id="sidebar-collapse-btn">
      <i class="fa fa-bars"></i>
    </button>
  </div>
  <div class="header-block header-block-search hidden-sm-down">
    <form role="search">
      <div class="input-container"><i class="fa fa-search"></i> <input type="search" placeholder="Search">
        <div class="underline"></div>
      </div>
    </form>
  </div>
  <div class="header-block header-block-buttons">
    <a href="https://github.com/modularcode/modular-admin-html" class="btn btn-sm header-btn">
      <i class="fa fa-github-alt"></i>
      <span>View on GitHub</span>
    </a> <a href="https://github.com/modularcode/modular-admin-html/stargazers" class="btn btn-sm header-btn">
    <i class="fa fa-star"></i>
    <span>Star Us</span>
  </a>
    <a href="https://github.com/modularcode/modular-admin-html/releases/download/v1.1.0/modular-admin-html-1.1.0.zip" class="btn btn-sm header-btn">
      <i class="fa fa-cloud-download"></i>
      <span>Download .zip</span>
    </a></div>
  <div class="header-block header-block-nav">
    <ul class="nav-profile">
      <li class="notifications new"><a href="" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <sup>
          <span class="counter">8</span>
        </sup>
      </a>
        <div class="dropdown-menu notifications-dropdown-menu">
          <ul class="notifications-container">
            <li>
              <a href="" class="notification-item">
                <div class="img-col">
                  <div class="img" style="background-image: url('assets/faces/3.jpg')"></div>
                </div>
                <div class="body-col">
                  <p><span class="accent">Zack Alien</span> pushed new commit:
                    <span class="accent">Fix page load performance issue</span>. </p>
                </div>
              </a>
            </li>
            <li>
              <a href="" class="notification-item">
                <div class="img-col">
                  <div class="img" style="background-image: url('assets/faces/5.jpg')"></div>
                </div>
                <div class="body-col">
                  <p><span class="accent">Amaya Hatsumi</span> started new task:
                    <span class="accent">Dashboard UI design.</span>. </p>
                </div>
              </a>
            </li>
            <li>
              <a href="" class="notification-item">
                <div class="img-col">
                  <div class="img" style="background-image: url('assets/faces/8.jpg')"></div>
                </div>
                <div class="body-col">
                  <p><span class="accent">Andy Nouman</span> deployed new version of
                    <span class="accent">NodeJS REST Api V3</span></p>
                </div>
              </a>
            </li>
          </ul>
          <footer>
            <ul>
              <li><a href="">
                View All
              </a></li>
            </ul>
          </footer>
        </div>
      </li>
      <li class="profile dropdown">
        <%= render 'layouts/dashboard/profile'%>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/dashboard/_profile.html.erb
<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
  <div class="img" style="background-image: url('https://avatars3.githubusercontent.com/u/3959008?v=3&s=40')"></div>
  <span class="name">
    			      <%= current_user.name %>
    			    </span> </a>
<div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
  <a class="dropdown-item" href="#">
    <i class="fa fa-user icon"></i>
    Profile
  </a> <a class="dropdown-item" href="#">
  <i class="fa fa-bell icon"></i>
  Notifications
</a> <a class="dropdown-item" href="#">
  <i class="fa fa-gear icon"></i>
  Settings
</a>
  <div class="dropdown-divider"></div>
  <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
    <i class="fa fa-power-off icon"></i>
    Logout
  <% end %></div>

app/views/layouts/dashboard/_sidebar.html.erb
<aside class="sidebar">
  <div class="sidebar-container">
    <div class="sidebar-header">
      <div class="brand">
        <div class="cupci-logo"><%= image_tag 'icon', class: 'align-top' %></div>
        <span>Cup CI</span>
      </div>
    </div>
    <nav class="menu">
      <ul class="nav metismenu" id="sidebar-menu">
        <li class="<%= 'active open' if controller_name == 'actions' %>">
          <%= link_to space_actions_path do %>
            <i class="fa fa-terminal"></i> Build Actions
          <% end %>
        </li>
        <li class="<%= 'active open' if controller_name == 'pipelines' %>">
          <%= link_to space_pipelines_path do %>
            <i class="fa fa-coffee"></i> Pipelines
          <% end %>
        </li>
        <li class="<%= 'active open' if controller_name == 'templates' %>">
          <%= link_to space_templates_path do %>
            <i class="fa fa-cubes"></i> Templates
          <% end %>
        </li>
        <li class="<%= 'active open' if controller_name == 'spaces' %>">
          <%= link_to spaces_path do %>
            <i class="fa fa-group"></i> WorkSpaces
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
  <footer class="sidebar-footer">
    <ul class="nav metismenu" id="customize-menu">
      <li>
        <a href="">
          <i class="fa fa-book"></i> Document
        </a></li>
    </ul>
  </footer>
</aside>
<div class="sidebar-overlay" id="sidebar-overlay"></div>