config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  # mostly resource under space namespace
  resources :spaces, only: [:new, :create, :index] do
    resources :pipelines, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        get 'configuration'
      end
      resources :actions, only: [:new, :create], module: :pipelines
    end

    resources :actions, only: [:index, :show] do
      member do
        post 'rebuild'
      end
    end
    resources :templates, only: [:index]
  end

  get '/repos/github_repos', to: 'repos#github_repos', as: 'github_repos'

  get 'dashboard', to: 'dashboard#index'
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/space.rb
# == Schema Information
#
# Table name: spaces
#
#  id         :integer          not null, primary key
#  name       :string
#  deleted_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_spaces_on_deleted_at  (deleted_at)
#

class Space < ApplicationRecord
  # many to many with users
  has_many :spaces_users
  has_many :users, through: :spaces_users

  # associations
  has_many :pipelines
  has_many :repos
  has_many :actions
  has_many :projects

  attr_accessor :owner

  after_commit :set_space_admin, on: :create

  acts_as_paranoid

  validates :name, presence: true
  validate :validate_admin_spaces_name, on: :create

  def admins
    spaces_users.where(role: :admin).includes(:user).map(&:user)
  end

  private
  def set_space_admin
    spaces_users.where(user: owner).first.admin!
  end

  def validate_admin_spaces_name
    if owner.blank?
      errors[:owner] << 'Space must have an owner'
      return
    end
    if owner.spaces.where(name: name).exists?
      errors[:name] << 'You already have a workspace with this name'
    end
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController

  def index
    @spaces = current_user.spaces
  end

  def create
    @space = current_user.spaces.create space_params.merge(owner: current_user)
  end

  private
  def space_params
    params.require(:space).permit(:name)
  end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_new_space.html.erb
<div class="modal fade" id="new-space-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Workspace</h4>
      </div>
      <div class="modal-body">
        <%= form_for(current_user.spaces.new, remote: true) do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control underlined', placeholder: 'Workspace name' %>
            <p class="alert-danger" data-error-message>
            </p>
          </div>
          <div class="form-group">
            <%= f.submit 'Create', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

app/views/spaces/create.js.erb
<%if @space.persisted?%>
location.reload();
<%else%>
$("p[data-error-message]").html("<%=raw @space.errors.messages.values.join('<br />') %>")
<%end%>

app/views/spaces/index.html.erb
<article class="content cards-page">
  <div class="title-block">
    <div class="row">
      <div class="col-md-6">
        <h3 class="title"> WorkSpaces
          <a href="#" class="btn btn-primary btn-sm rounded-s" data-toggle="modal" data-target="#new-space-modal">
            Add New
          </a>
        </h3>
        <p class="title-description"> Switch workspaces </p>
      </div>
    </div>
  </div>
  <section class="section">
    <% @spaces.each do |space| %>
      <div class="row">
        <div class="col-xl-4">
          <div class="card card-default">
            <div class="card-header">
              <div class="header-block">
                <p class="title"> <%= link_to space.name, dashboard_path(space_id: space.id) %> </p>
              </div>
            </div>
            <div class="card-block">
              <p>Users: <%= space.users.count %><br> Created: <%= time_ago_in_words space.created_at %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <% if @spaces.blank? %>
      <div class="row">
        <div class="col-xl-4">
          <div class="card card-warning">
            <div class="card-header">
              <div class="header-block">
                <p class="title"> No workspaces </p>
              </div>
            </div>
            <div class="card-block">
              <p>Click 'Add New' to add a workspace</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </section>
</article>

<%= render 'new_space' %>