config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  # mostly resource under space namespace
  resources :spaces, only: [:new, :create, :index] do
    resources :pipelines, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        get 'configuration'
      end
      resources :actions, only: [:new, :create], module: :pipelines
    end

    resources :actions, only: [:index, :show] do
      member do
        post 'rebuild'
      end
    end
    resources :templates, only: [:index]
  end

  get '/repos/github_repos', to: 'repos#github_repos', as: 'github_repos'

  get 'dashboard', to: 'dashboard#index'
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :check_user_current_space

  def index
    @q = current_space.actions.ransack(params[:q])
    @actions = @q.result.order(id: :desc).includes(:pipeline).page(params[:page])
  end

  def show
    set_action
  end

  def rebuild
    set_action
    @action.start_build!
  end

  private
  def set_action
    @action = current_space.actions.find(params[:id])
  end
end

app/controllers/pipelines/actions_controller.rb
class Pipelines::ActionsController < ApplicationController
  def new
    set_pipeline
    build_action
  end

  def create
    set_pipeline
    build_action
    if @action.save
      @action.start_build!
    end
  end

  private

  def set_pipeline
    @pipeline = current_space.pipelines.find(params[:pipeline_id])
  end

  def build_action
    @action ||= @pipeline.actions.new
    @action.attributes = action_params.merge(space: current_space, triggerable: current_user, configuration: action_configuration_params)
  end

  def action_params
    {}
  end

  def action_configuration_params
    if params.dig(:action_attributes, :configuration)
      params.require(:action_attributes).require(:configuration).permit!
    else
      nil
    end
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/pipelines/actions_helper.rb
module Pipelines::ActionsHelper
end

app/views/actions/_action_row.html.erb
<li class="item" data-action-id="<%= action.id %>">
  <div class="item-row">
    <div class="item-col no-overflow">
      <div class="item-heading">Status</div>
      <div>
        <%= link_to space_action_path(current_space, action) do %>
          <%= action.status %>
        <% end %>
      </div>
    </div>
    <div class="item-col no-overflow">
      <div class="item-heading">Name</div>
      <div class="no-overflow">
        <%= link_to space_action_path(action) do %>
          <small><%= action.name %></small>
        <% end %>
      </div>
    </div>
    <div class="item-col">
      <div class="item-heading">Commit</div>
      <div class="no-overflow"><%= action&.configuration&.dig('git_commit') %></div>
    </div>
    <div class="item-col">
      <div class="item-heading">Trigger By</div>
      <div> <%= action.triggerable.name %></div>
    </div>
    <div class="item-col">
      <div class="item-heading">Started</div>
      <div class="no-overflow">
        <small><%= (at = action.started_at) ? time_ago_in_words(at) : 'Not Yet' %></small>
      </div>
    </div>
    <div class="item-col fixed item-col-actions-dropdown">
      <div class="item-actions-dropdown"><a class="item-actions-toggle-btn">
								<span class="inactive">
									<i class="fa fa-cog"></i>
								</span>
        <span class="active">
								<i class="fa fa-chevron-circle-right"></i>
								</span>
      </a>
        <div class="item-actions-block">
          <ul class="item-actions-list">
            <li>
              <%= link_to rebuild_space_action_path(current_space, action), class: 'edit', remote: true, method: :post do %>
                <i class="fa fa-refresh"></i>
              <% end %>
            </li>
            <li>
              <%= link_to space_pipeline_path(current_space, action.pipeline), class: 'edit' do %>
                <i class="fa fa-coffee"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/actions/index.html.erb
<article class="content items-list-page">
  <div class="title-search-block">
    <div class="title-block">
      <div class="row">
        <div class="col-md-6">
          <h3 class="title"> Build Actions
          </h3>
          <p class="title-description"> Pipeline build actions </p>
        </div>
      </div>
    </div>
    <div class="items-search">
      <%= search_form_for @q, url: space_actions_path(current_space), class: 'form-inline' do |f| %>
        <div class="input-group">
          <%= f.search_field :pipeline_name_cont, class: "form-control boxed rounded-s", placeholder: "Search for...", autofocus: 'autofocus' %>
          <span class="input-group-btn">
            <%= f.submit class: "btn btn-secondary rounded-s" do %>
						<i class="fa fa-search"></i>
					<% end %>
				  </span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="card items">
    <ul class="item-list striped">
      <li class="item item-list-header hidden-sm-down">
        <div class="item-row">
          <div class="item-col item-col-header">
            <div><span>Status</span></div>
          </div>
          <div class="item-col item-col-header">
            <div class="no-overflow"><span>Name</span></div>
          </div>
          <div class="item-col item-col-header">
            <div class="no-overflow"><span>Commit</span></div>
          </div>
          <div class="item-col item-col-header">
            <div class="no-overflow"><span>Trigger by</span></div>
          </div>
          <div class="item-col item-col-header">
            <div><span>Started</span></div>
          </div>
          <div class="item-col item-col-header fixed item-col-actions-dropdown"></div>
        </div>
      </li>
      <% @actions.each do |action| %>
        <%= render 'action_row', action: action %>
      <% end %>
    </ul>
  </div>
  <%= paginate @actions %>
</article>

app/views/actions/show.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title">
      <%= @action.name %>
      <%= link_to 'Back', :back, class: 'btn btn-secondary btn-sm rounded-s' %>
    </h3>
  </div>

  <div class="card card-block">
    <div class="subtitle-block">
      <h3 class="subtitle"> Job #<%=@action.sequence%> </h3>
    </div>

    <div class="form-group">
      Repo: <%= @action.pipeline.source.reponame %>
    </div>

    <div class="form-group">
      Status: <%= @action.status %>
    </div>

    <div class="form-group">
      Created At: <%= @action.created_at %>
    </div>

    <div class="form-group">
      Ran For: <%= @action.completed? ? @action.ran_seconds : 'Not yet finished' %>
    </div>

    <div class="form-group">
      Pipeline: <%= link_to @action.pipeline.name, space_pipeline_path(current_space, @action.pipeline) %>
    </div>

    <div class="subtitle-block">
      <h3 class="subtitle"> Job Log </h3>
    </div>
    <!-- pipeline basic settings -->

    <div class="form-group">
      logs....
    </div>
  </div>
</article>