config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }

  # mostly resource under space namespace
  resources :spaces, only: [:new, :create, :index] do
    resources :pipelines, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        get 'configuration'
      end
      resources :actions, only: [:new, :create], module: :pipelines
    end

    resources :actions, only: [:index, :show] do
      member do
        post 'rebuild'
      end
    end
    resources :templates, only: [:index]
  end

  get '/repos/github_repos', to: 'repos#github_repos', as: 'github_repos'

  get 'dashboard', to: 'dashboard#index'
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pipeline.rb
# == Schema Information
#
# Table name: pipelines
#
#  id            :integer          not null, primary key
#  name          :string
#  space_id      :integer
#  source_type   :string
#  source_id     :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  ancestry      :string
#  template_id   :integer
#  user_id       :integer
#  project_id    :integer
#  configuration :jsonb
#
# Indexes
#
#  index_pipelines_on_ancestry                   (ancestry)
#  index_pipelines_on_project_id                 (project_id)
#  index_pipelines_on_source_type_and_source_id  (source_type,source_id)
#  index_pipelines_on_space_id                   (space_id)
#  index_pipelines_on_template_id                (template_id)
#  index_pipelines_on_user_id                    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (project_id => projects.id)
#  fk_rails_...  (space_id => spaces.id)
#  fk_rails_...  (template_id => templates.id)
#  fk_rails_...  (user_id => users.id)
#

class Pipeline < ApplicationRecord
  belongs_to :space
  belongs_to :user
  belongs_to :source, polymorphic: true
  belongs_to :template
  belongs_to :project
  has_many :actions

  has_ancestry

  validates :space_id, :name, :template_id, :project_id, :user_id, presence: true

  # execute pipeline
  def start
    actions.create.tap do |action|
      PipelineWorker.perform_async action_id: action.id
    end
  end
end

app/controllers/pipelines/actions_controller.rb
class Pipelines::ActionsController < ApplicationController
  def new
    set_pipeline
    build_action
  end

  def create
    set_pipeline
    build_action
    if @action.save
      @action.start_build!
    end
  end

  private

  def set_pipeline
    @pipeline = current_space.pipelines.find(params[:pipeline_id])
  end

  def build_action
    @action ||= @pipeline.actions.new
    @action.attributes = action_params.merge(space: current_space, triggerable: current_user, configuration: action_configuration_params)
  end

  def action_params
    {}
  end

  def action_configuration_params
    if params.dig(:action_attributes, :configuration)
      params.require(:action_attributes).require(:configuration).permit!
    else
      nil
    end
  end
end

app/controllers/pipelines_controller.rb
class PipelinesController < ApplicationController
  before_action :check_user_current_space

  def create
    set_template
    build_pipeline

    if save_pipeline
      redirect_to action: :index
    else
      render :new
    end
  end

  def new
    set_template
    @pipeline = Pipeline.new template: @template
  end

  def show
    set_pipeline
  end

  def edit
    set_pipeline
  end

  def configuration
    set_pipeline
  end

  def destroy
    set_pipeline
    @pipeline.destroy

    respond_to do |format|
      format.html do
        redirect_to action: :index
      end

      format.js
    end
  end

  def update
    set_template
    set_pipeline
    build_pipeline
    if save_pipeline
      redirect_to action: :show
    else
      render :edit
    end
  end

  def index
    @q = current_space.pipelines.ransack(params[:q])
    @pipelines = @q.result.order(updated_at: :desc).includes(:project).page(params[:page])
  end

  private
  # save pipeline and dependencies
  def save_pipeline
    valid = true
    valid = @pipeline.source.valid? && valid
    valid = @pipeline.project.valid? && valid
    valid = @pipeline.valid? && valid
    if valid
      Pipeline.transaction do
        @pipeline.source.save!
        @pipeline.project.save!
        @pipeline.save!
      end
      true
    else
      false
    end
  end

  def build_pipeline
    @pipeline ||= current_space.pipelines.new
    source = load_pipeline_source
    project = find_or_create_project
    @pipeline.attributes = pipeline_params.merge(
      template: @template, source: source, user: current_user, project: project,
      configuration: pipeline_configuration_params)
  end

  def load_pipeline_source
    auth = current_user.auths.find repo_params[:auth_id]
    attributes = {auth: auth, reponame: repo_params[:reponame]}

    # build or update repo as source for each pipeline
    source = @pipeline&.source || current_space.repos.new
    source.attributes = attributes
    source
  end

  def find_or_create_project
    name = params.dig(:pipeline, :project, :name)
    current_space.projects.where(user: current_user).find_or_create_by name: name
  end

  def set_template
    @template = Template.templates(current_space).find(params.dig(:pipeline, :template_id))
  end

  def set_pipeline
    @pipeline = current_space.pipelines.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pipeline_params
    params.require(:pipeline).permit(:name)
  end

  def pipeline_configuration_params
    if params.dig(:pipeline, :configuration).present?
      params.require(:pipeline).require(:configuration).permit!
    else
      nil
    end
  end

  def repo_params
    params.require(:pipeline).require(:source).permit(:reponame, :auth_id)
  end
end

app/helpers/pipelines/actions_helper.rb
module Pipelines::ActionsHelper
end

app/helpers/pipelines_helper.rb
module PipelinesHelper
  def render_pipeline_status(pipeline)
    if (running_count = pipeline.actions.running.count) > 0
      "<span class=\"text-success\">Running (#{running_count})</span>"
    else
      "<span>Not Running</span>"
    end.html_safe
  end
end

app/views/pipelines/_form.html.erb
<% template ||= pipeline.template %>
<% url = pipeline.new_record? ? space_pipelines_path : space_pipeline_path(current_space, pipeline) %>
<% edit ||= false %>

<%= simple_form_for pipeline, url: url, name: 'item' do |f| %>
  <div class="card card-block">

    <div class="form-group">
      <div class="images-container">
        <%= render 'templates/template', template: template %>
      </div>
      <%= f.input :template_id, as: :hidden %>
    </div>

    <div class="subtitle-block">
      <h3 class="subtitle"> Source </h3>
    </div>

    <div class="form-group">
      <ul class="nav nav-pills" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="pill" href="#github-repo" role="tab">GitHub</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="pill" href="#bitbucket-repo" role="tab">Bitbucket</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="pill" href="#git-repo" role="tab">Git</a>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane fade show active in" id="github-repo" role="tabpanel">
          <%= f.simple_fields_for :source do |ff| %>
            <%= ff.input :reponame, label: 'Repo', input_html: {value: pipeline.source&.reponame}, disabled: !edit %>
            <%= ff.input :auth_id, input_html: {value: current_user.auths.with_provider('github').first!.id}, as: :hidden %>
            <%= ff.input :type, input_html: {value: 'repo'}, as: :hidden %>
          <% end %>
        </div>
        <div class="tab-pane fade" id="bitbucket-repo">...</div>
        <div class="tab-pane fade" id="git-repo">...</div>
      </div>
    </div>

    <div class="subtitle-block">
      <h3 class="subtitle"> Basic </h3>
    </div>
    <!-- pipeline basic settings -->

    <div class="form-group">
      <%= f.input :name, class: 'form-control boxed', placeholder: 'Name', disabled: !edit %>
    </div>

    <div class="form-group">
      <%= f.simple_fields_for :project do |ff| %>
        <%= ff.label :name do %>
          <abbr title="required">*</abbr>
          Project
        <% end %>
        <%= ff.input_field :name, collection: current_space.projects.pluck(:name), selected: @pipeline.project&.name, id: 'select-projects', disabled: !edit %>
      <% end %>
    </div>

    <!--pipeline basic settings end -->
    <div class="subtitle-block">
      <h3 class="subtitle"> Action </h3>
    </div>
    <%= f.simple_fields_for Decorator::JsonField.new(pipeline.configuration) do |ff| %>
      <div class="form-group">
        <%= ff.input :scripts, as: :scripts, disabled: !edit %>
      </div>
      <div class="form-group">
        <%= ff.input :docker_image, class: 'form-control boxed', placeholder: 'Docker Image', disabled: !edit %>
      </div>
    <% end %>
    <div class="form-group row">
      <div class="col-sm-10 col-sm-offset-2">
        <%= f.button :submit, class: 'btn btn-primary' if edit %>
      </div>
    </div>
  </div>
<% end %>

app/views/pipelines/_nav.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'View', space_pipeline_path(current_space, pipeline), class: "nav-link#{' active' if action_name == 'show'}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Edit', edit_space_pipeline_path(current_space, pipeline), class: "nav-link#{' active' if action_name == 'edit' || action_name == 'update'}" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Config', configuration_space_pipeline_path(current_space, pipeline), class: "nav-link#{' active' if action_name == 'configuration'}" %>
  </li>
</ul>

app/views/pipelines/_pipeline_row.html.erb
<li class="item" data-pipeline-id="<%= pipeline.id %>">
  <div class="item-row">
    <!--<div class="item-col fixed item-col-check"><label class="item-check" id="select-all-items">-->
    <!--<input type="checkbox" class="checkbox">-->
    <!--<span></span>-->
    <!--</label></div>-->
    <div class="item-col fixed pull-left item-col-title">
      <div class="item-heading">Name</div>
      <div>
        <%= link_to space_pipeline_path(pipeline) do %>
          <h4 class="item-title"> <%= pipeline.name %> </h4>
        <% end %>
      </div>
    </div>
    <div class="item-col no-overflow">
      <div class="item-heading">Project</div>
      <div class="no-overflow"><%= pipeline.project.name %></div>
    </div>
    <div class="item-col">
      <div class="item-heading">Creator</div>
      <div class="no-overflow"><%= pipeline.user.name %></div>
    </div>
    <div class="item-col">
      <div class="item-heading">Status</div>
      <div> <%= render_pipeline_status(pipeline) %></div>
    </div>
    <div class="item-col">
      <div class="item-heading">Updated</div>
      <div class="no-overflow"> <small><%= (at = pipeline.updated_at) ? time_ago_in_words(at) : 'Never' %></small></div>
    </div>
    <div class="item-col fixed item-col-actions-dropdown">
      <div class="item-actions-dropdown"><a class="item-actions-toggle-btn">
								<span class="inactive">
									<i class="fa fa-cog"></i>
								</span>
        <span class="active">
								<i class="fa fa-chevron-circle-right"></i>
								</span>
      </a>
        <div class="item-actions-block">
          <ul class="item-actions-list">
            <li>
              <%= link_to new_space_pipeline_action_path(current_space, pipeline), class: 'edit', remote: true do %>
                <i class="fa fa-gamepad"></i>
              <% end %>
            </li>
            <li>
              <%= link_to edit_space_pipeline_path(current_space, pipeline), class: 'edit' do %>
                <i class="fa fa-pencil"></i>
              <% end %>
            </li>
            <li>
              <%= link_to space_pipeline_path(current_space, pipeline), class: 'remove', remote: true, method: :delete, data: {confirm: 'Are you sure?'} do %>
                <i class="fa fa-trash-o "></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/pipelines/configuration.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title"> Config Pipeline
      - <%= @pipeline.name %> <%= link_to 'Back', :back, class: 'btn btn-secondary btn-sm rounded-s' %></h3>
  </div>
  <%= render 'nav', pipeline: @pipeline %>
  <div class="card card-block">
    <div class="form-group">
      <%= link_to 'Delete Pipeline', space_pipeline_path(current_space, @pipeline),
                  data: {confirm: 'Sure?'}, method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</article>

app/views/pipelines/edit.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title"> Edit Pipeline
      - <%= @pipeline.name %> <%= link_to 'Back', :back, class: 'btn btn-secondary btn-sm rounded-s' %></h3>
  </div>
  <%= render 'nav', pipeline: @pipeline %>
  <%= render 'form', pipeline: @pipeline, template: @template, edit: true %>
</article>

app/views/pipelines/index.html.erb
<article class="content items-list-page">
  <div class="title-search-block">
    <div class="title-block">
      <div class="row">
        <div class="col-md-6">
          <h3 class="title"> Pipelines
            <a href="<%= space_templates_path %>" class="btn btn-primary btn-sm rounded-s">
              Add New
            </a>
            <!--
-->
            <!--<div class="action dropdown">-->
            <!--<button class="btn  btn-sm rounded-s btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
            <!--More actions...-->
            <!--</button>-->
            <!--<div class="dropdown-menu" aria-labelledby="dropdownMenu1">-->
            <!--<a class="dropdown-item" href="#"><i class="fa fa-pencil-square-o icon"></i>Mark as a draft</a>-->
            <!--<a class="dropdown-item" href="#" data-toggle="modal" data-target="#confirm-modal"><i class="fa fa-close icon"></i>Delete</a>-->
            <!--</div>-->
            <!--</div>-->
          </h3>
          <p class="title-description"> Create a pipeline to start CI/CD </p>
        </div>
      </div>
    </div>
    <div class="items-search">
      <%= search_form_for @q, url: space_pipelines_path(current_space), class: 'form-inline' do |f| %>
        <div class="input-group">
          <%= f.search_field :name_or_project_name_cont, class: "form-control boxed rounded-s", placeholder: "Search for...", autofocus: 'autofocus' %>
          <span class="input-group-btn">
            <%= f.submit class: "btn btn-secondary rounded-s" do %>
						<i class="fa fa-search"></i>
					<% end %>
				  </span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="card items">
    <ul class="item-list striped">
      <li class="item item-list-header hidden-sm-down">
        <div class="item-row">
          <!--<div class="item-col fixed item-col-check"><label class="item-check" id="select-all-items">-->
          <!--<input type="checkbox" class="checkbox">-->
          <!--<span></span>-->
          <!--</label></div>-->
          <div class="item-col item-col-header item-col-title">
            <div><span>Name</span></div>
          </div>
          <div class="item-col item-col-header">
            <div class="no-overflow"><span>Project</span></div>
          </div>
          <div class="item-col item-col-header">
            <div class="no-overflow"><span>Creator</span></div>
          </div>
          <div class="item-col item-col-header">
            <div><span>Status</span></div>
          </div>
          <div class="item-col item-col-header">
            <div><span>Updated</span></div>
          </div>
          <div class="item-col item-col-header fixed item-col-actions-dropdown"></div>
        </div>
      </li>
      <% @pipelines.each do |pipeline| %>
        <%= render 'pipeline_row', pipeline: pipeline %>
      <% end %>
    </ul>
  </div>
  <%= paginate @pipelines %>
</article>
<div id="new-action-modal" class="modal fade"></div>

app/views/pipelines/new.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title"> Add new pipeline <%= link_to 'Back', :back, class: 'btn btn-secondary btn-sm rounded-s' %></h3>
  </div>
  <%= render 'form', pipeline: @pipeline, template: @template, edit: true %>
</article>

app/views/pipelines/show.html.erb
<article class="content item-editor-page">
  <div class="title-block">
    <h3 class="title"> Pipeline
      - <%= @pipeline.name %> <%= link_to 'Back', :back, class: 'btn btn-secondary btn-sm rounded-s' %></h3>
  </div>
  <%= render 'nav', pipeline: @pipeline %>
  <%= render 'form', pipeline: @pipeline, template: @template %>
</article>